# Generated by Django 5.1.5 on 2025-02-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialproperty",
            name="distance_from_road",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="commercialproperty",
            name="has_security",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commercialproperty",
            name="nearby",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="commercialproperty",
            name="nearby_amenities",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="commercialproperty",
            name="power_backup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="industrialproperty",
            name="distance_from_road",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="industrialproperty",
            name="nearby",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="industrialproperty",
            name="nearby_amenities",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="industrialproperty",
            name="power_backup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="residentialproperty",
            name="distance_from_road",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="residentialproperty",
            name="has_security",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="residentialproperty",
            name="nearby",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="residentialproperty",
            name="nearby_amenities",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
